	mysystem u0 (
		.clock_bridge_0_in_clk_clk          (<connected-to-clock_bridge_0_in_clk_clk>),          //    clock_bridge_0_in_clk.clk
		.fifo_fpga_to_hps_in_writedata      (<connected-to-fifo_fpga_to_hps_in_writedata>),      //      fifo_fpga_to_hps_in.writedata
		.fifo_fpga_to_hps_in_write          (<connected-to-fifo_fpga_to_hps_in_write>),          //                         .write
		.fifo_fpga_to_hps_in_waitrequest    (<connected-to-fifo_fpga_to_hps_in_waitrequest>),    //                         .waitrequest
		.fifo_fpga_to_hps_in_csr_address    (<connected-to-fifo_fpga_to_hps_in_csr_address>),    //  fifo_fpga_to_hps_in_csr.address
		.fifo_fpga_to_hps_in_csr_read       (<connected-to-fifo_fpga_to_hps_in_csr_read>),       //                         .read
		.fifo_fpga_to_hps_in_csr_writedata  (<connected-to-fifo_fpga_to_hps_in_csr_writedata>),  //                         .writedata
		.fifo_fpga_to_hps_in_csr_write      (<connected-to-fifo_fpga_to_hps_in_csr_write>),      //                         .write
		.fifo_fpga_to_hps_in_csr_readdata   (<connected-to-fifo_fpga_to_hps_in_csr_readdata>),   //                         .readdata
		.fifo_hps_to_fpga_out_readdata      (<connected-to-fifo_hps_to_fpga_out_readdata>),      //     fifo_hps_to_fpga_out.readdata
		.fifo_hps_to_fpga_out_read          (<connected-to-fifo_hps_to_fpga_out_read>),          //                         .read
		.fifo_hps_to_fpga_out_waitrequest   (<connected-to-fifo_hps_to_fpga_out_waitrequest>),   //                         .waitrequest
		.fifo_hps_to_fpga_out_csr_address   (<connected-to-fifo_hps_to_fpga_out_csr_address>),   // fifo_hps_to_fpga_out_csr.address
		.fifo_hps_to_fpga_out_csr_read      (<connected-to-fifo_hps_to_fpga_out_csr_read>),      //                         .read
		.fifo_hps_to_fpga_out_csr_writedata (<connected-to-fifo_hps_to_fpga_out_csr_writedata>), //                         .writedata
		.fifo_hps_to_fpga_out_csr_write     (<connected-to-fifo_hps_to_fpga_out_csr_write>),     //                         .write
		.fifo_hps_to_fpga_out_csr_readdata  (<connected-to-fifo_hps_to_fpga_out_csr_readdata>),  //                         .readdata
		.hex5_0bus_export                   (<connected-to-hex5_0bus_export>),                   //                hex5_0bus.export
		.memory_mem_a                       (<connected-to-memory_mem_a>),                       //                   memory.mem_a
		.memory_mem_ba                      (<connected-to-memory_mem_ba>),                      //                         .mem_ba
		.memory_mem_ck                      (<connected-to-memory_mem_ck>),                      //                         .mem_ck
		.memory_mem_ck_n                    (<connected-to-memory_mem_ck_n>),                    //                         .mem_ck_n
		.memory_mem_cke                     (<connected-to-memory_mem_cke>),                     //                         .mem_cke
		.memory_mem_cs_n                    (<connected-to-memory_mem_cs_n>),                    //                         .mem_cs_n
		.memory_mem_ras_n                   (<connected-to-memory_mem_ras_n>),                   //                         .mem_ras_n
		.memory_mem_cas_n                   (<connected-to-memory_mem_cas_n>),                   //                         .mem_cas_n
		.memory_mem_we_n                    (<connected-to-memory_mem_we_n>),                    //                         .mem_we_n
		.memory_mem_reset_n                 (<connected-to-memory_mem_reset_n>),                 //                         .mem_reset_n
		.memory_mem_dq                      (<connected-to-memory_mem_dq>),                      //                         .mem_dq
		.memory_mem_dqs                     (<connected-to-memory_mem_dqs>),                     //                         .mem_dqs
		.memory_mem_dqs_n                   (<connected-to-memory_mem_dqs_n>),                   //                         .mem_dqs_n
		.memory_mem_odt                     (<connected-to-memory_mem_odt>),                     //                         .mem_odt
		.memory_mem_dm                      (<connected-to-memory_mem_dm>),                      //                         .mem_dm
		.memory_oct_rzqin                   (<connected-to-memory_oct_rzqin>),                   //                         .oct_rzqin
		.pushbutton_export                  (<connected-to-pushbutton_export>),                  //               pushbutton.export
		.ram_s2_address                     (<connected-to-ram_s2_address>),                     //                   ram_s2.address
		.ram_s2_chipselect                  (<connected-to-ram_s2_chipselect>),                  //                         .chipselect
		.ram_s2_clken                       (<connected-to-ram_s2_clken>),                       //                         .clken
		.ram_s2_write                       (<connected-to-ram_s2_write>),                       //                         .write
		.ram_s2_readdata                    (<connected-to-ram_s2_readdata>),                    //                         .readdata
		.ram_s2_writedata                   (<connected-to-ram_s2_writedata>),                   //                         .writedata
		.ram_s2_byteenable                  (<connected-to-ram_s2_byteenable>),                  //                         .byteenable
		.sdram_wire_addr                    (<connected-to-sdram_wire_addr>),                    //               sdram_wire.addr
		.sdram_wire_ba                      (<connected-to-sdram_wire_ba>),                      //                         .ba
		.sdram_wire_cas_n                   (<connected-to-sdram_wire_cas_n>),                   //                         .cas_n
		.sdram_wire_cke                     (<connected-to-sdram_wire_cke>),                     //                         .cke
		.sdram_wire_cs_n                    (<connected-to-sdram_wire_cs_n>),                    //                         .cs_n
		.sdram_wire_dq                      (<connected-to-sdram_wire_dq>),                      //                         .dq
		.sdram_wire_dqm                     (<connected-to-sdram_wire_dqm>),                     //                         .dqm
		.sdram_wire_ras_n                   (<connected-to-sdram_wire_ras_n>),                   //                         .ras_n
		.sdram_wire_we_n                    (<connected-to-sdram_wire_we_n>),                    //                         .we_n
		.system_ref_clk_clk                 (<connected-to-system_ref_clk_clk>),                 //           system_ref_clk.clk
		.system_ref_reset_reset             (<connected-to-system_ref_reset_reset>),             //         system_ref_reset.reset
		.to_hex_to_led_readdata             (<connected-to-to_hex_to_led_readdata>),             //            to_hex_to_led.readdata
		.sdram_clk_clk                      (<connected-to-sdram_clk_clk>)                       //                sdram_clk.clk
	);

